# Generated by Django 4.2.5 on 2023-10-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomodation_name', models.TextField(default='', max_length=100)),
                ('accomodation_description', models.TextField(default='', max_length=10000)),
                ('accomodation_price', models.IntegerField()),
                ('accomodation_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
