# Generated by Django 4.2.5 on 2023-10-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='newsletter_category',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='newsletter_picture',
            field=models.ImageField(blank=True, null=True, upload_to='newsletter/images/'),
        ),
    ]
