# Generated by Django 4.2.5 on 2023-10-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_remove_newsletter_newsletter_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='newsletter_picture',
            field=models.ImageField(blank=True, null=True, upload_to='newsletter/images/'),
        ),
    ]
