# Generated by Django 4.2.5 on 2023-10-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_newsletter_newsletter_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='newsletter_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
