# Generated by Django 4.1.1 on 2023-10-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadium_name', models.TextField(default='', max_length=100)),
                ('stadium_overview', models.TextField(default='', max_length=10000)),
                ('stadium_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('stadium_map', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
