# Generated by Django 4.1.1 on 2023-10-11 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StadiumFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='stadium.stadium')),
            ],
        ),
    ]
