# Generated by Django 4.1.1 on 2023-10-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0002_stadiumfeature'),
        ('user', '0004_staffprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stadium.stadium'),
        ),
    ]
