# Generated by Django 4.1.1 on 2023-10-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_staffprofile_stadium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
