# Generated by Django 4.1.1 on 2023-10-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_staffprofile_id_alter_staffprofile_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='disability',
            field=models.CharField(default='mobility disabled', max_length=30),
            preserve_default=False,
        ),
    ]
