# Generated by Django 4.1.1 on 2023-10-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_account_disability'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default='null', upload_to='images/'),
            preserve_default=False,
        ),
    ]
